package Java_programming;
import java.util.Scanner;
import java.util.Random;

/*
Create a class Game, which allows a user to play "Guess the Number" game once.

Game should have the following methods:
Constructor to generate the random number
takeUserInput() to take a user input of number
isCorrectNumber() to detect whether the number entered by the user is true
getter and setter for noOfGuesses
Use properties such as noOfGuesses(int), etc to get this task done!
 */

class Game{
    public int RandomNumber;
    public int no_of_Guess;
    int UserGuess = 0;


    // method to take guess from user -------------------------
    public void UserInput(int i){
        UserGuess = i;
    }

    //constructor for Genrating random number  -------------
    public Game (){
        Random rc = new Random();
        RandomNumber = rc.nextInt(10);
    }

    // method to check weather users guess is right or wrong ----------------
    /* this while method will check weather the number chosen by user is equal to number
     generated by computer is right or wrong like wise will update the value of no_of_guess
     every time and return true or false as result */

    public boolean IsCorrectNumber(){

        if(UserGuess>RandomNumber){
            System.out.println("Your number is bigger than the Magic number");
            no_of_Guess = no_of_Guess +1;
            return false;
        }
        else if (UserGuess<RandomNumber) {
            System.out.println("Your number is lesser..Try Again!!");
            no_of_Guess = no_of_Guess +1;
            return false;
        }
        else{
            System.out.println("Your guess is right!! & You Won the Match!!");
            no_of_Guess = no_of_Guess +1;
            System.out.println("Number of guess required : "+no_of_Guess);
            return true;
        }
    }
}

public class CWH_43_ExerciseGame {
    public static void main(String[] args) {

        System.out.println("********************************");
        System.out.println("Game--> Magic Guess");
        System.out.println("Guess the number: ");

        Scanner sc = new Scanner(System.in);

 /* by creating object player we have called Game constructor and -------------
         the Game() constructor contain definition to generate a random number
         so random number will be generated  as we know when object is created com.company.Constructor is called*/
        Game player = new Game();

        // this will take input from user as guess ---------------------
        System.out.println("Guess the Number from 0 to 10 :  ");
        player.UserInput(sc.nextInt());

    /* this loop will run until the condition become true -------------------
        if IsCorrectGuess function return false then it will call function Spark_2_0_Java_Full_Stack_.UserInput() until result gets true
        and according to condition update the value of no_of_guess
          */
        while(!player.IsCorrectNumber()){ // this condition will run when this condition is false because it assign the symbol(!) means opposite (false__True/True__false)
            System.out.println("Guess the Number Again");
            player.UserInput(sc.nextInt());
        }
    }
}
